const productDetailData = [
  {
    'product_id': 1,
    'product_name' : 'Apple iphone14Pro',
    'product_storage' : ['128GB','256GB','512GB','1TB'],
    'product_color' : ['Black','Purple','Red','White','Yellow'],
    'color' : 'Black',
    'product_screenSize' : '6.1',
    'product_cpu' : 'Apple A16 Bionic',
    'product_numberOfCores' : 6,
    'product_mainCamera' : '48MP~',
    'product_FrontCamera' : '12MP',
    'product_batteryCapacity' : '3,200mAh',
    'product_price' : 1437,
    'thumbnail' : 'assets/images/iphone14_black.jpg.avif',
  },
  {
    'product_id': 2,
    'product_name' : 'Apple iphone14Pro',
    'product_storage' : ['128GB','256GB','512GB','1TB'],
    'product_color' : ['Black','Purple','Red','White','Yellow'],
    'color' : 'Yellow',
    'product_screenSize' : '6.1',
    'product_cpu' : 'Apple A16 Bionic',
    'product_numberOfCores' : 6,
    'product_mainCamera' : '48MP~',
    'product_FrontCamera' : '12MP',
    'product_batteryCapacity' : '3,200mAh',
    'product_price' : 1437,
    'thumbnail' : 'assets/images/iphone14pro_yellow.jpg.avif',
  },
  {
    'product_id': 3,
    'product_name' : 'Apple iphone14Pro',
    'product_storage' : ['128GB','256GB','512GB','1TB'],
    'product_color' : ['Black','purple','red','White','yellow'],
    'color' : 'red',
    'product_screenSize' : '6.1',
    'product_cpu' : 'Apple A16 Bionic',
    'product_numberOfCores' : 6,
    'product_mainCamera' : '48MP~',
    'product_FrontCamera' : '12MP',
    'product_batteryCapacity' : '3,200mAh',
    'product_price' : 1437,
    'thumbnail' : 'assets/images/iphone14_red.jpg.avif',
  },
  {
    'product_id': 4,
    'product_name' : 'Apple iphone14Pro',
    'product_storage' : ['128GB','256GB','512GB','1TB'],
    'product_color' : ['Black','Purple','Red','White','Yellow'],
    'color' : 'White',
    'product_screenSize' : '6.1',
    'product_cpu' : 'Apple A16 Bionic',
    'product_numberOfCores' : 6,
    'product_mainCamera' : '48MP~',
    'product_FrontCamera' : '12MP',
    'product_batteryCapacity' : '3,200mAh',
    'product_price' : 1437,
    'thumbnail' : 'assets/images/iphone14_white.jpg.avif',
  },
  {
    'product_id': 5,
    'product_name' : 'Apple iphone14Pro',
    'product_storage' : ['128GB','256GB','512GB','1TB'],
    'product_color' : ['Black','Purple','Red','White','Yellow'],
    'color' : 'Purple',
    'product_screenSize' : '6.1',
    'product_cpu' : 'Apple A16 Bionic',
    'product_numberOfCores' : 6,
    'product_mainCamera' : '48MP~',
    'product_FrontCamera' : '12MP',
    'product_batteryCapacity' : '3,200mAh',
    'product_price' : 1437,
    'thumbnail' : 'assets/images/iphone14_purple.jpg.avif',
  },
  {
    'product_id': 6,
    'product_name' : 'Apple iphone11',
    'product_storage' : ['128GB','256GB','512GB','1TB'],
    'product_color' : ['Black','White',],
    'color' : 'Black',
    'product_screenSize' : '6.1',
    'product_cpu' : 'Apple A16 Bionic',
    'product_numberOfCores' : 6,
    'product_mainCamera' : '48MP~',
    'product_FrontCamera' : '12MP',
    'product_batteryCapacity' : '3,200mAh',
    'product_price' : 510,
    'thumbnail' : 'assets/images/iphone11_black.jpg.avif',
  },
  {
    'product_id': 7,
    'product_name' : 'Apple iphone11',
    'product_storage' : ['128GB','256GB','512GB','1TB'],
    'product_color' : ['Black','White',],
    'color' : 'White',
    'product_screenSize' : '6.1',
    'product_cpu' : 'Apple A16 Bionic',
    'product_numberOfCores' : 6,
    'product_mainCamera' : '48MP~',
    'product_FrontCamera' : '12MP',
    'product_batteryCapacity' : '3,200mAh',
    'product_price' : 550,
    'thumbnail' : 'assets/images/iphone 14 pro_white.png',
  },

];